
export const cultures = {
    'af-ZA': 'Afrikaans - South Africa',
    'ar-AE': 'Arabic - United Arab Emirates',
    'ar-BH': 'Arabic - Bahrain',
    'ar-DZ': 'Arabic - Algeria',
    'ar-EG': 'Arabic - Egypt',
    'ar-IQ': 'Arabic - Iraq',
    'ar-JO': 'Arabic - Jordan',
    'ar-KW': 'Arabic - Kuwait',
    'ar-LB': 'Arabic - Lebanon',
    'ar-LY': 'Arabic - Libya',
    'ar-MA': 'Arabic - Morocco',
    'ar-OM': 'Arabic - Oman',
    'ar-QA': 'Arabic - Qatar',
    'ar-SA': 'Arabic - Saudi Arabia',
    'ar-SY': 'Arabic - Syria',
    'ar-TN': 'Arabic - Tunisia',
    'ar-YE': 'Arabic - Yemen',
    'az-AZ': 'Azeri - Azerbaijan',
    'be-BY': 'Belarusian - Belarus',
    'bg-BG': 'Bulgarian - Bulgaria',
    'bs-BA': 'Bosnian - Bosnia and Herzegovina',
    'ca-ES': 'Catalan - Spain',
    'cs-CZ': 'Czech - Czech Republic',
    'cy-GB': 'Welsh - United Kingdom',
    'da-DK': 'Danish - Denmark',
    'de-AT': 'German - Austria',
    'de-CH': 'German - Switzerland',
    'de-DE': 'German - Germany',
    'de-LI': 'German - Liechtenstein',
    'de-LU': 'German - Luxembourg',
    'dv-MV': 'Divehi - Maldives',
    'el-GR': 'Greek - Greece',
    'en-AU': 'English - Australia',
    'en-BZ': 'English - Belize',
    'en-CA': 'English - Canada',
    'en-CB': 'English - Caribbean',
    'en-GB': 'English - United Kingdom',
    'en-IE': 'English - Ireland',
    'en-JM': 'English - Jamaica',
    'en-NZ': 'English - New Zealand',
    'en-PH': 'English - Republic of the Philippines',
    'en-TT': 'English - Trinidad and Tobago',
    'en-US': 'English - United States',
    'en-ZA': 'English - South Africa',
    'en-ZW': 'English - Zimbabwe',
    'es-AR': 'Spanish - Argentina',
    'es-BO': 'Spanish - Bolivia',
    'es-CL': 'Spanish - Chile',
    'es-CO': 'Spanish - Colombia',
    'es-CR': 'Spanish - Costa Rica',
    'es-DO': 'Spanish - Dominican Republic',
    'es-EC': 'Spanish - Ecuador',
    'es-ES': 'Spanish - Spain',
    'es-GT': 'Spanish - Guatemala',
    'es-HN': 'Spanish - Honduras',
    'es-MX': 'Spanish - Mexico',
    'es-NI': 'Spanish - Nicaragua',
    'es-PA': 'Spanish - Panama',
    'es-PE': 'Spanish - Peru',
    'es-PR': 'Spanish - Puerto Rico',
    'es-PY': 'Spanish - Paraguay',
    'es-SV': 'Spanish - El Salvador',
    'es-UY': 'Spanish - Uruguay',
    'es-VE': 'Spanish - Venezuela',
    'et-EE': 'Estonian - Estonia',
    'eu-ES': 'Basque - Spain',
    'fa-IR': 'Farsi - Iran',
    'fi-FI': 'Finnish - Finland',
    'fo-FO': 'Faroese - Faroe Islands',
    'fr-BE': 'French - Belgium',
    'fr-CA': 'French - Canada',
    'fr-CH': 'French - Switzerland',
    'fr-FR': 'French - France',
    'fr-LU': 'French - Luxembourg',
    'fr-MC': 'French - Principality of Monaco',
    'gl-ES': 'Galician - Spain',
    'gu-IN': 'Gujarati - India',
    'he-IL': 'Hebrew - Israel',
    'hi-IN': 'Hindi - India',
    'hr-BA': 'Croatian - Bosnia and Herzegovina',
    'hr-HR': 'Croatian - Croatia',
    'hu-HU': 'Hungarian - Hungary',
    'hy-AM': 'Armenian - Armenia',
    'id-ID': 'Indonesian - Indonesia',
    'is-IS': 'Icelandic - Iceland',
    'it-CH': 'Italian - Switzerland',
    'it-IT': 'Italian - Italy',
    'ja-JP': 'Japanese - Japan',
    'ka-GE': 'Georgian - Georgia',
    'kk-KZ': 'Kazakh - Kazakhstan',
    'kn-IN': 'Kannada - India',
    'ko-KR': 'Korean - Korea',
    'ky-KG': 'Kyrgyz - Kyrgyzstan',
    'ky-KZ': 'Kyrgyz - Kazakhstan',
    'lt-LT': 'Lithuanian - Lithuania',
    'lv-LV': 'Latvian - Latvia',
    'mi-NZ': 'Maori - New Zealand',
    'mk-MK': 'Macedonian - Former Yugoslav Republic of Macedonia',
    'mn-MN': 'Mongolian - Mongolia',
    'mr-IN': 'Marathi - India',
    'ms-BN': 'Malay - Brunei Darussalam',
    'ms-MY': 'Malay - Malaysia',
    'mt-MT': 'Maltese - Malta',
    'nb-NO': 'Norwegian (Bokmål) - Norway',
    'nl-BE': 'Dutch - Belgium',
    'nl-NL': 'Dutch - Netherlands',
    'nn-NO': 'Norwegian (Nynorsk) - Norway',
    'ns-ZA': 'Northern Sotho - South Africa',
    'pa-IN': 'Punjabi - India',
    'pl-PL': 'Polish - Poland',
    'ps-AF': 'Pashto - Afghanistan',
    'pt-BR': 'Portuguese - Brazil',
    'pt-PT': 'Portuguese - Portugal',
    'qu-BO': 'Quechua - Bolivia',
    'qu-EC': 'Quechua - Ecuador',
    'qu-PE': 'Quechua - Peru',
    'ro-RO': 'Romanian - Romania',
    'ru-RU': 'Russian - Russia',
    'sa-IN': 'Sanskrit - India',
    'se-FI': 'Sami - Finland',
    'se-NO': 'Sami - Norway',
    'se-SE': 'Sami - Sweden',
    'sk-SK': 'Slovak - Slovakia',
    'sl-SI': 'Slovenian - Slovenia',
    'sq-AL': 'Albanian - Albania',
    'sr-BA': 'Serbian - Bosnia and Herzegovina',
    'sr-RS': 'Serbian - Serbia',
    'sv-FI': 'Swedish - Finland',
    'sv-SE': 'Swedish - Sweden',
    'sw-KE': 'Swahili - Kenya',
    'syr-SY': 'Syriac - Syria',
    'ta-IN': 'Tamil - India',
    'te-IN': 'Telugu - India',
    'th-TH': 'Thai - Thailand',
    'tl-PH': 'Tagalog - Republic of the Philippines',
    'tn-ZA': 'Tswana - South Africa',
    'tr-TR': 'Turkish - Turkey',
    'tt-RU': 'Tatar - Russia',
    'uk-UA': 'Ukrainian - Ukraine',
    'ur-PK': 'Urdu - Islamic Republic of Pakistan',
    'uz-UZ': 'Uzbek - Uzbekistan',
    'vi-VN': 'Vietnamese - Vietnam',
    'xh-ZA': 'Xhosa - South Africa',
    'zh-CN': 'Chinese - China',
    'zh-HK': 'Chinese - Hong Kong',
    'zh-MO': 'Chinese - Macau',
    'zh-SG': 'Chinese - Singapore',
    'zh-TW': 'Chinese - Taiwan',
    'zu-ZA': 'Zulu - South Africa'
}

export type CultureCode = keyof typeof cultures

export function getCultureCodes(): CultureCode[] {
    return Object.keys(cultures) as CultureCode[]
}

export function getCultureName(code: CultureCode) {
    return cultures[code]
}
